"use client"
import "primereact/resources/themes/tailwind-light/theme.css";     
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";  
import "primeflex/primeflex.css";
import "./globals.css";
import Header from "../components/Header";
import Providers from "../redux/Providers";

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }
  
export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <head />
      <body>
      <Providers>
        <Header/>
        {children}
        </Providers>
        </body>
    </html>
  )
}
